# Generated by Django 5.2 on 2025-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=100)),
                ('destination_zip', models.CharField(max_length=10)),
                ('cost_usd', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('method', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FreightCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('container_type', models.CharField(max_length=20)),
                ('cost_usd', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('hs_code', models.CharField(max_length=20)),
                ('rate_percent', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('date_effective', models.DateField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
